FROM python:3.10-slim

WORKDIR /app/data_get/jwt_microservice/

# Install dependencies using the renamed requirements file
COPY requirements_jwt_microservice.txt .
RUN pip install --no-cache-dir -r requirements_jwt_microservice.txt

# Copy the microservice code
COPY data_get/jwt_microservice/ .

# Run the API
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
